### ISSUE TITLE
v1.4 C7 missing?

### ISSUE THREAD

**Issue by kwadsten** [rallepalaveev/analog#2]
Hi, your schematic (A2VGA.v1.4-hardware/A2VGA.v1.4.sch.pdf) shows a 220u C7, but I'm not seeing that on the pcb anywhere.

**Comment by Verault** [comment]
I noticed that as well. I assume it was a leftover from a previous version. Either way dont worry, it will build fine without it. Something else to note is I have seen boards labeled ver 1.2 and having two completely different values for the resistors. (R15 to R22). That is puzzling. How can there be two different versions of 1.2 gerbers?

**Comment by rallepalaveev** [comment]
C7 missing is not a problem. The values of the resistors - I had to tweak them, work in progress.
