### ISSUE TITLE
A2USB: Adding USB support to A2VGA cards...

### ISSUE THREAD

**Issue by ThorstenBr** [rallepalaveev/analog#3]
Hi Ralle,

I created a new firmware project - adding USB support for the PICO-based A2VGA cards. It currently emulates an Apple II Mouse Interface Card, using a standard USB mouse:

- The firmware project is available here: https://github.com/ThorstenBr/A2USB
- I also wrote a blog post about the project details: https://www.applefritter.com/content/a2usb-apple-ii-usb-mouse-interface-card-emulation

Proper mouse support on the Apple II requires an IRQ option. I simply rigged this to my existing PCBs, using a MOSFET and two resistors. When the USB firmware is used, the VGA output pins are no longer needed. So I reused the former VGA VSYNC output pin to trigger the IRQ instead.

Would you be interested in a small collaboration? I don't want to start another A2VGA PCB project - just to add a jumper and an optional MOSFET. I think it would be nice if the existing PCB projects just added the IRQ option. It would make these boards even more attractive. And obviously there are other possible applications. The USB support and Mouse Card emulation is only one such example.

Maybe have a look at the project and blog links above. Also contains a simple schematic showing what I added for the IRQ option. Let me know if you were interested in extending your PCB design.

Happy 2024!

**Comment by rallepalaveev** [comment]
Hi Thorsten,

Happy new 2024!

Thanks for your message - this is a very interesting firmware that you have built, I was myself thinking of the many potential applications of the hardware in this fashion - software defined hardware, including of course a mouse emulation, so congratulations on achieving this milestone!

Meanwhile I have been working intensively for some time with Oliver Schmidt on a design, which includes IRQ functionality with the same idea - to have a simple hardware which can emulate many cards, depending on the software it is running. This is based on my initial A2Pico designs: https://github.com/rallepalaveev/a2pico , but the goal was to avoid the programmable logic altogether and achieve a really simple design. We have successfully done this on a TH board by using only the GPIOs and no programmable logic, based on Oliver's original code with some expansion. 

So in case you are interested - Oliver and I would be very happy if you would join our collaboration and perhaps contribute to it. I propose that have an initial discussion by e-mail and see where this gets us, please reach me on rpalaveev@clintech.net

Thank you!

Ralle

**Comment by rallepalaveev** [comment]
Addressed by A2VGA.v1.6.
