### ISSUE TITLE
I just had a few ver 1.6 PCBs printed that came in last night. I checked the github today and you deleted the hardware ver 1.6 folder five days ago. What happened?

### ISSUE THREAD

**Issue by Verault** [rallepalaveev/analog#5]
I just had some ver 1.6 PCBs printed that were delivered to me last night. I just checked the github today and you deleted the hardware ver 1.6 folder. What happened? Is there some kind of problem with the circuit design of Ver 1.6?

**Comment by rallepalaveev** [comment]
The design is still good, I just have removed temporarily. If you need any files, let me know.
